-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 12:11:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`config` (
  `CODCONFIG` INT NOT NULL,
  `NMEMPRESA` VARCHAR(255) NOT NULL,
  `TITULOSITE` VARCHAR(255) NULL,
  `EMAIL` VARCHAR(255) NULL,  
  `NMFANTASIA` VARCHAR(255) NULL,
  `TELFIXO` VARCHAR(45) NULL,
  `WHATSAPP` VARCHAR(45) NULL,
  `TITULOMAPS` VARCHAR(255) NOT NULL,
  `MAPA` LONGTEXT NULL,
  `SMTP` VARCHAR(255) NULL,
  `EMAILENVIO` VARCHAR(255) NULL,
  `SENHAEMAIL` VARCHAR(255) NULL,
  `PORTA` VARCHAR(45) NULL,
  `BCC` VARCHAR(255) NULL,
  `FACEBOOK` VARCHAR(300) NULL,
  `INSTAGRAM` VARCHAR(255) NULL,
  PRIMARY KEY (`CODCONFIG`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
